#!/bin/sh

args=("$@")
JLL_PATH=${args[0]}
PROGNAME="`sed '6q;d' data.txt`"
PACKNAME="`sed '4q;d' data.txt`"
USERNAME="`sed '2q;d' data.txt`"
printf "[JL/ANDR] Porting $PROGNAME ($PACKNAME/$USERNAME) to Android....\n"
USERPROG="`pwd -P`"
NDK_PATH=$JLL_PATH/deps/android-ndk-r10e
SDK_PATH=$JLL_PATH/deps/android-sdk-linux
ANDROID_PROJECT=$JLL_PATH/build/android
ANDROID_HOME=$SDK_PATH

sh $JLL_PATH/compile-scripts/jl_android_.sh\
 NDK_DEBUG=0 "$JLL_PATH" "$PROGNAME" "$PACKNAME" "$USERNAME" "$USERPROG"\
 "$NDK_PATH" "$SDK_PATH" "$ANDROID_PROJECT" "$ANDROID_HOME"\
 false 
cd $ANDROID_PROJECT

printf "[JL/ANDR] zipalign: creating release....\n"
$SDK_PATH/build-tools/23.0.2/zipalign -v 4 bin/jlw.$USERNAME.$PACKNAME-release-unsigned.apk bin/jlw.$USERNAME.$PACKNAME-release.apk

printf "[JL/ANDR] finished!  Installing...\n"
$SDK_PATH/platform-tools/adb install -r bin/jlw.$USERNAME.$PACKNAME-release.apk
#ant release install

printf "[JL/ANDR] Starting Up\n"
$SDK_PATH/platform-tools/adb shell am start -a android.intent.action.MAIN -n jlw.$USERNAME.$PACKNAME/.jl_Activity

printf "[JL/ANDR] Cleaning Up...\n"
cd $USERPROG
### clean-up ###
# java #
rm -f $ANDROID_PROJECT/src/jlw/$USERNAME/$PACKNAME/jl_Activity.java
rmdir $ANDROID_PROJECT/src/jlw/$USERNAME/$PACKNAME/
rmdir $ANDROID_PROJECT/src/jlw/$USERNAME/
# C #
rm -f $ANDROID_PROJECT/jni/src/gen/src/*

printf "[JL/ANDR] DONE!\n"

$SDK_PATH/platform-tools/adb logcat | grep I\/SDL\/APP
